const mockClassList = [
    {
       id: "1",
       count: 23, 
    },
    {
        id: "2",
        count: 34,
    },
    {
        id: "3",
        count: 45,
    }
]

const mockStudentList = [
    {
        id: "1",
        name: "Test Name",
        nickname: "nick",
        role: "Student",
        password: "",
        class: "1",
    },
    {
        id: "2",
        name: "Test Name",
        nickname: "nick",
        role: "Student",
        password: "",
        class: "1",
    },
    {
        id: "3",
        name: "Test Name",
        nickname: "nick",
        role: "Student",
        password: "",
        class: "1",
    },
    {
        id: "4",
        name: "Test Name",
        nickname: "nick",
        role: "Student",
        password: "",
        class: "1",
    },
    {
        id: "5",
        name: "Test Name",
        nickname: "nick",
        role: "Student",
        password: "",
        class: "1",
    },
    {
        id: "6",
        name: "Test Name",
        nickname: "nick",
        role: "Student",
        password: "",
        class: "1",
    },
    {
        id: "7",
        name: "Test Name",
        nickname: "nick",
        role: "Student",
        password: "",
        class: "1",
    },
    {
        id: "8",
        name: "Test Name",
        nickname: "nick",
        role: "Student",
        password: "",
        class: "1",
    },
    {
        id: "9",
        name: "Test Name",
        nickname: "nick",
        role: "Student",
        password: "",
        class: "1",
    },
        {
        id: "10",
        name: "Test Name",
        nickname: "nick",
        role: "Student",
        password: "",
        class: "1",
    },
    {
        id: "11",
        name: "Test Name",
        nickname: "nick",
        role: "Student",
        password: "",
        class: "1",
    },
    {
        id: "12",
        name: "Test Name",
        nickname: "nick",
        role: "Student",
        password: "",
        class: "1",
    },
    {
        id: "13",
        name: "Test Name",
        nickname: "nick",
        role: "Student",
        password: "",
        class: "1",
    },
    {
        id: "14",
        name: "Test Name",
        nickname: "nick",
        role: "Student",
        password: "",
        class: "1",
    },
    {
        id: "15",
        name: "Test Name",
        nickname: "nick",
        role: "Student",
        password: "",
        class: "1",
    },
    {
        id: "16",
        name: "Test Name",
        nickname: "nick",
        role: "Student",
        password: "",
        class: "1",
    },
    {
        id: "17",
        name: "Test Name",
        nickname: "nick",
        role: "Student",
        password: "",
        class: "1",
    },
    {
        id: "18",
        name: "Test Name",
        nickname: "nick",
        role: "Student",
        password: "",
        class: "1",
    },
]

const mockUserData = {
    id: "1",
    name: "Test Name",
    nickname: "nick",
    role: "Student",
    password: "",
    class: "1",
}

export const mock = {
    mockClassList,
    mockStudentList,
    mockUserData
}
